### ISSUE TITLE
need another column added to get helmreleases

### ISSUE THREAD

**Issue by ronhorton** [aiyengar2/helm-locker#6]
current:
ronaldhorton@ronalds-MBP example % kubectl get helmreleases -A
NAMESPACE            NAME         RELEASE STATUS
cattle-helm-system   my-release   Deployed
kube-system          my-release
\
for clarity, add a column for the namespace of the chart to be monitored. eg, cattle-monitoring-system.

**Comment by aiyengar2** [comment]
Should have been added already!

**Comment by ronhorton** [comment]
verified. 

![Screen Shot 2022-04-15 at 1 15 18 PM](https://user-images.githubusercontent.com/89212856/163600674-d82dd621-642b-473c-ab81-909e4964c42d.png)
