### ISSUE TITLE
helm-locker TLS handshake timeout - failed to update lock

### ISSUE THREAD

**Issue by ronhorton** [aiyengar2/helm-locker#7]
INFO[48281] applied cattle-monitoring-system/rancher-monitoring
E0415 08:42:35.218052    4898 leaderelection.go:367] Failed to update lock: Put "https://ronhead2.qa.rancher.space/k8s/clusters/c-k56pq/api/v1/namespaces/cattle-helm-system/configmaps/helm-locker-lock": net/http: TLS handshake timeout

Saw this this morning.

**Comment by aiyengar2** [comment]
This seems like an ephemeral error that may not be consistently reproducible, but I will try to reproduce it if I have time before release!

I would consider this a low-priority issue though unless it can be consistently reproduced in a given setup; it may also have to do with the nature of testing via a binary on your local machine as opposed to a Helm chart deployment.

**Comment by aiyengar2** [comment]
Closed in favor of https://github.com/rancher/helm-locker/issues/5
